/* SPDX-License-Identifier: BSD-3-Clause
 * Copyright(c) 2025 Huawei Technologies Co., Ltd
 */

#ifndef _HINIC3_FLOW_H_
#define _HINIC3_FLOW_H_

#include <rte_flow.h>

/* Flow item type. */
#define HINIC3_FLOW_ITEM_TYPE_END                  RTE_FLOW_ITEM_TYPE_END
#define HINIC3_FLOW_ITEM_TYPE_VOID                 RTE_FLOW_ITEM_TYPE_VOID
#define HINIC3_FLOW_ITEM_TYPE_INVERT               RTE_FLOW_ITEM_TYPE_INVERT
#define HINIC3_FLOW_ITEM_TYPE_ANY                  RTE_FLOW_ITEM_TYPE_ANY
#define HINIC3_FLOW_ITEM_TYPE_PF                   RTE_FLOW_ITEM_TYPE_PF
#define HINIC3_FLOW_ITEM_TYPE_VF                   RTE_FLOW_ITEM_TYPE_VF
#define HINIC3_FLOW_ITEM_TYPE_PHY_PORT             RTE_FLOW_ITEM_TYPE_PHY_PORT
#define HINIC3_FLOW_ITEM_TYPE_PORT_ID              RTE_FLOW_ITEM_TYPE_PORT_ID
#define HINIC3_FLOW_ITEM_TYPE_RAW                  RTE_FLOW_ITEM_TYPE_RAW
#define HINIC3_FLOW_ITEM_TYPE_ETH                  RTE_FLOW_ITEM_TYPE_ETH
#define HINIC3_FLOW_ITEM_TYPE_VLAN                 RTE_FLOW_ITEM_TYPE_VLAN
#define HINIC3_FLOW_ITEM_TYPE_IPV4                 RTE_FLOW_ITEM_TYPE_IPV4
#define HINIC3_FLOW_ITEM_TYPE_IPV6                 RTE_FLOW_ITEM_TYPE_IPV6
#define HINIC3_FLOW_ITEM_TYPE_ICMP                 RTE_FLOW_ITEM_TYPE_ICMP
#define HINIC3_FLOW_ITEM_TYPE_UDP                  RTE_FLOW_ITEM_TYPE_UDP
#define HINIC3_FLOW_ITEM_TYPE_TCP                  RTE_FLOW_ITEM_TYPE_TCP
#define HINIC3_FLOW_ITEM_TYPE_SCTP                 RTE_FLOW_ITEM_TYPE_SCTP
#define HINIC3_FLOW_ITEM_TYPE_VXLAN                RTE_FLOW_ITEM_TYPE_VXLAN
#define HINIC3_FLOW_ITEM_TYPE_E_TAG                RTE_FLOW_ITEM_TYPE_E_TAG
#define HINIC3_FLOW_ITEM_TYPE_NVGRE                RTE_FLOW_ITEM_TYPE_NVGRE
#define HINIC3_FLOW_ITEM_TYPE_MPLS                 RTE_FLOW_ITEM_TYPE_MPLS
#define HINIC3_FLOW_ITEM_TYPE_GRE                  RTE_FLOW_ITEM_TYPE_GRE
#define HINIC3_FLOW_ITEM_TYPE_FUZZY                RTE_FLOW_ITEM_TYPE_FUZZY
#define HINIC3_FLOW_ITEM_TYPE_GTP                  RTE_FLOW_ITEM_TYPE_GTP
#define HINIC3_FLOW_ITEM_TYPE_GTPC                 RTE_FLOW_ITEM_TYPE_GTPC
#define HINIC3_FLOW_ITEM_TYPE_GTPU                 RTE_FLOW_ITEM_TYPE_GTPU
#define HINIC3_FLOW_ITEM_TYPE_ESP                  RTE_FLOW_ITEM_TYPE_ESP
#define HINIC3_FLOW_ITEM_TYPE_GENEVE               RTE_FLOW_ITEM_TYPE_GENEVE
#define HINIC3_FLOW_ITEM_TYPE_VXLAN_GPE            RTE_FLOW_ITEM_TYPE_VXLAN_GPE
#define HINIC3_FLOW_ITEM_TYPE_ARP_ETH_IPV4         RTE_FLOW_ITEM_TYPE_ARP_ETH_IPV4
#define HINIC3_FLOW_ITEM_TYPE_IPV6_EXT             RTE_FLOW_ITEM_TYPE_IPV6_EXT
#define HINIC3_FLOW_ITEM_TYPE_ICMP6                RTE_FLOW_ITEM_TYPE_ICMP6
#define HINIC3_FLOW_ITEM_TYPE_ICMP6_ND_NS          RTE_FLOW_ITEM_TYPE_ICMP6_ND_NS
#define HINIC3_FLOW_ITEM_TYPE_ICMP6_ND_NA          RTE_FLOW_ITEM_TYPE_ICMP6_ND_NA
#define HINIC3_FLOW_ITEM_TYPE_ICMP6_ND_OPT         RTE_FLOW_ITEM_TYPE_ICMP6_ND_OPT
#define HINIC3_FLOW_ITEM_TYPE_ICMP6_ND_OPT_SLA_ETH RTE_FLOW_ITEM_TYPE_ICMP6_ND_OPT_SLA_ETH
#define HINIC3_FLOW_ITEM_TYPE_ICMP6_ND_OPT_TLA_ETH RTE_FLOW_ITEM_TYPE_ICMP6_ND_OPT_TLA_ETH
#define HINIC3_FLOW_ITEM_TYPE_MARK                 RTE_FLOW_ITEM_TYPE_MARK
#define HINIC3_FLOW_ITEM_TYPE_META                 RTE_FLOW_ITEM_TYPE_META
#define HINIC3_FLOW_ITEM_TYPE_GRE_KEY              RTE_FLOW_ITEM_TYPE_GRE_KEY
#define HINIC3_FLOW_ITEM_TYPE_GTP_PSC              RTE_FLOW_ITEM_TYPE_GTP_PSC
#define HINIC3_FLOW_ITEM_TYPE_PPPOES               RTE_FLOW_ITEM_TYPE_PPPOES
#define HINIC3_FLOW_ITEM_TYPE_PPPOED               RTE_FLOW_ITEM_TYPE_PPPOED
#define HINIC3_FLOW_ITEM_TYPE_PPPOE_PROTO_ID       RTE_FLOW_ITEM_TYPE_PPPOE_PROTO_ID
#define HINIC3_FLOW_ITEM_TYPE_NSH                  RTE_FLOW_ITEM_TYPE_NSH
#define HINIC3_FLOW_ITEM_TYPE_IGMP                 RTE_FLOW_ITEM_TYPE_IGMP
#define HINIC3_FLOW_ITEM_TYPE_AH                   RTE_FLOW_ITEM_TYPE_AH
#define HINIC3_FLOW_ITEM_TYPE_HIGIG2               RTE_FLOW_ITEM_TYPE_HIGIG2
#define HINIC3_FLOW_ITEM_TYPE_TAG                  RTE_FLOW_ITEM_TYPE_TAG

/* Flow error type. */
#define HINIC3_FLOW_ERROR_TYPE_NONE                RTE_FLOW_ERROR_TYPE_NONE
#define HINIC3_FLOW_ERROR_TYPE_UNSPECIFIED         RTE_FLOW_ERROR_TYPE_UNSPECIFIED
#define HINIC3_FLOW_ERROR_TYPE_HANDLE              RTE_FLOW_ERROR_TYPE_HANDLE
#define HINIC3_FLOW_ERROR_TYPE_ATTR_GROUP          RTE_FLOW_ERROR_TYPE_ATTR_GROUP
#define HINIC3_FLOW_ERROR_TYPE_ATTR_PRIORITY       RTE_FLOW_ERROR_TYPE_ATTR_PRIORITY
#define HINIC3_FLOW_ERROR_TYPE_ATTR_INGRESS        RTE_FLOW_ERROR_TYPE_ATTR_INGRESS
#define HINIC3_FLOW_ERROR_TYPE_ATTR_EGRESS         RTE_FLOW_ERROR_TYPE_ATTR_EGRESS
#define HINIC3_FLOW_ERROR_TYPE_ATTR_TRANSFER       RTE_FLOW_ERROR_TYPE_ATTR_TRANSFER
#define HINIC3_FLOW_ERROR_TYPE_ATTR                RTE_FLOW_ERROR_TYPE_ATTR
#define HINIC3_FLOW_ERROR_TYPE_ITEM_NUM            RTE_FLOW_ERROR_TYPE_ITEM_NUM
#define HINIC3_FLOW_ERROR_TYPE_ITEM_SPEC           RTE_FLOW_ERROR_TYPE_ITEM_SPEC
#define HINIC3_FLOW_ERROR_TYPE_ITEM_LAST           RTE_FLOW_ERROR_TYPE_ITEM_LAST
#define HINIC3_FLOW_ERROR_TYPE_ITEM_MASK           RTE_FLOW_ERROR_TYPE_ITEM_MASK
#define HINIC3_FLOW_ERROR_TYPE_ITEM                RTE_FLOW_ERROR_TYPE_ITEM
#define HINIC3_FLOW_ERROR_TYPE_ACTION_NUM          RTE_FLOW_ERROR_TYPE_ACTION_NUM
#define HINIC3_FLOW_ERROR_TYPE_ACTION_CONF         RTE_FLOW_ERROR_TYPE_ACTION_CONF
#define HINIC3_FLOW_ERROR_TYPE_ACTION              RTE_FLOW_ERROR_TYPE_ACTION

#endif /**< _HINIC3_FLOW_H_ */
