;
; Features of a default network driver.
;
; This file defines the features that are valid for inclusion in
; the other driver files and also the order that they appear in
; the features table in the documentation. The feature description
; string should not exceed feature_str_len defined in conf.py.
;
[Features]
Speed capabilities   =
Link status          =
Link status event    =
Removal event        =
Queue status event   =
Rx interrupt         =
Lock-free Tx queue   =
Fast mbuf free       =
Free Tx mbuf on demand =
Queue start/stop     =
Runtime Rx queue setup =
Runtime Tx queue setup =
Burst mode info      =
MTU update           =
Jumbo frame          =
Scattered Rx         =
LRO                  =
TSO                  =
Promiscuous mode     =
Allmulticast mode    =
Unicast MAC filter   =
Multicast MAC filter =
RSS hash             =
RSS key update       =
RSS reta update      =
Inner RSS            =
VMDq                 =
SR-IOV               =
DCB                  =
VLAN filter          =
Flow control         =
Flow API             =
Rate limitation      =
Traffic mirroring    =
Inline crypto        =
Inline protocol      =
CRC offload          =
VLAN offload         =
QinQ offload         =
L3 checksum offload  =
L4 checksum offload  =
Timestamp offload    =
MACsec offload       =
Inner L3 checksum    =
Inner L4 checksum    =
Packet type parsing  =
Timesync             =
Rx descriptor status =
Tx descriptor status =
Basic stats          =
Extended stats       =
Stats per queue      =
FW version           =
EEPROM dump          =
Module EEPROM dump   =
Registers dump       =
LED                  =
Multiprocess aware   =
FreeBSD              =
Linux                =
Windows              =
ARMv7                =
ARMv8                =
Power8               =
x86-32               =
x86-64               =
Usage doc            =
Design doc           =
Perf doc             =

[rte_flow items]
any                  =
raw                  =
eth                  =
vlan                 =
ipv4                 =
ipv6                 =
icmp                 =
udp                  =
tcp                  =
sctp                 =
vxlan                =
e_tag                =
nvgre                =
mpls                 =
gre                  =
gre_key              =
fuzzy                =
gtp                  =
gtpc                 =
gtpu                 =
esp                  =
geneve               =
vxlan-gpe            =
arp_eth_ipv4         =
ipv6_ext             =
ipv6_frag_ext        =
icmp6                =
icmp6_nd_ns          =
icmp6_nd_na          =
icmp6_nd_opt         =
icmp6_nd_opt_sla_eth =
icmp6_nd_opt_tla_eth =
meta                 =
gtp_psc              =
pppoes               =
pppoed               =
pppoe_proto_id       =
nsh                  =
igmp                 =
ah                   =
higig2               =
l2tpv3oip            =
pfcp                 =
ecpri                =

[rte_flow actions]
end                  =
void                 =
passthru             =
jump                 =
mark                 =
flag                 =
queue                =
drop                 =
count                =
rss                  =
pf                   =
vf                   =
phy_port             =
port_id              =
meter                =
security             =
of_set_mpls_ttl      =
of_dec_mpls_ttl      =
of_set_nw_ttl        =
of_dec_nw_ttl        =
of_copy_ttl_out      =
of_copy_ttl_in       =
of_pop_vlan          =
of_push_vlan         =
of_set_vlan_vid      =
of_set_vlan_pcp      =
of_pop_mpls          =
of_push_mpls         =
vxlan_encap          =
vxlan_decap          =
nvgre_encap          =
nvgre_decap          =
raw_encap            =
raw_decap            =
set_ipv4_src         =
set_ipv4_dst         =
set_ipv6_src         =
set_ipv6_dst         =
set_tp_src           =
set_tp_dst           =
mac_swap             =
dec_ttl              =
set_ttl              =
set_mac_src          =
set_mac_dst          =
inc_tcp_seq          =
dec_tcp_seq          =
inc_tcp_ack          =
dec_tcp_ack          =
set_tag              =
set_meta             =
set_ipv4_dscp        =
set_ipv6_dscp        =
age                  =
sample               =
shared               =
modify_field         =

[rte_flow shared actions]
age                  =
rss                  =
