;
; Supported features of the 'ioring' driver.
;
; Refer to default.ini for the full list of available PMD features.
;
[Features]
Link status          = Y
MTU update           = Y
Promiscuous mode     = Y
Allmulticast mode    = Y
Multiprocess aware   = Y
Basic stats          = Y
Stats per queue      = Y
Linux		     = Y
x86-64               = Y
Usage doc            = Y
