;
; Supported features of the 'mana' network poll mode driver.
;
; Refer to default.ini for the full list of available PMD features.
;
[Features]
Linux                = Y
Multiprocess aware   = Y
Usage doc            = Y
x86-64               = Y
