;
; Supported features of the 'sxe2' network poll mode driver.
;
; Refer to default.ini for the full list of available PMD features.
;
; A feature with "P" indicates only be supported when non-vector path
; is selected.
;
[Features]
Fast mbuf free       = P
Free Tx mbuf on demand = Y
Burst mode info      = Y
Queue start/stop     = Y
Buffer split on Rx   = P
Scattered Rx         = Y
CRC offload          = Y
VLAN offload         = Y
QinQ offload         = P
L3 checksum offload  = Y
L4 checksum offload  = Y
Timestamp offload    = P
Inner L3 checksum    = P
Inner L4 checksum    = P
Rx descriptor status = Y
Tx descriptor status = Y
FreeBSD              = Y
Linux                = Y
x86-32               = Y
x86-64               = Y
