/* SPDX-License-Identifier: BSD-3-Clause
 * Copyright(c) 2021 Ramaxel Memory Technology, Ltd
 */

#ifndef _SPNIC_CMD_H_
#define _SPNIC_CMD_H_

#define NIC_RSS_TEMP_ID_TO_CTX_LT_IDX(tmp_id)	tmp_id
/* Begin of one temp tbl */
#define NIC_RSS_TEMP_ID_TO_INDIR_LT_IDX(tmp_id)	((tmp_id) << 4)
/* 4 ctx in one entry */
#define NIC_RSS_CTX_TBL_ENTRY_SIZE		0x10
/* Entry size = 16B, 16 entry/template */
#define NIC_RSS_INDIR_TBL_ENTRY_SIZE		0x10
/* Entry size = 16B, so entry_num = 256B/16B */
#define NIC_RSS_INDIR_TBL_ENTRY_NUM		0x10

#define NIC_UP_RSS_INVALID_TEMP_ID		0xFF
#define NIC_UP_RSS_INVALID_FUNC_ID		0xFFFF
#define NIC_UP_RSS_INVALID			0x00
#define NIC_UP_RSS_EN				0x01
#define NIC_UP_RSS_INVALID_GROUP_ID		0x7F

#define NIC_RSS_CMD_TEMP_ALLOC			0x01
#define NIC_RSS_CMD_TEMP_FREE			0x02

#define SPNIC_RSS_TYPE_VALID_SHIFT		23
#define SPNIC_RSS_TYPE_TCP_IPV6_EXT_SHIFT	24
#define SPNIC_RSS_TYPE_IPV6_EXT_SHIFT		25
#define SPNIC_RSS_TYPE_TCP_IPV6_SHIFT		26
#define SPNIC_RSS_TYPE_IPV6_SHIFT		27
#define SPNIC_RSS_TYPE_TCP_IPV4_SHIFT		28
#define SPNIC_RSS_TYPE_IPV4_SHIFT		29
#define SPNIC_RSS_TYPE_UDP_IPV6_SHIFT		30
#define SPNIC_RSS_TYPE_UDP_IPV4_SHIFT		31
#define SPNIC_RSS_TYPE_SET(val, member)	\
	(((u32)(val) & 0x1) << SPNIC_RSS_TYPE_##member##_SHIFT)

#define SPNIC_RSS_TYPE_GET(val, member)	\
	(((u32)(val) >> SPNIC_RSS_TYPE_##member##_SHIFT) & 0x1)

/* NIC CMDQ MODE */
typedef enum spnic_ucode_cmd {
	SPNIC_UCODE_CMD_MODIFY_QUEUE_CTX = 0,
	SPNIC_UCODE_CMD_CLEAN_QUEUE_CONTEXT,
	SPNIC_UCODE_CMD_ARM_SQ,
	SPNIC_UCODE_CMD_ARM_RQ,
	SPNIC_UCODE_CMD_SET_RSS_INDIR_TABLE,
	SPNIC_UCODE_CMD_SET_RSS_CONTEXT_TABLE,
	SPNIC_UCODE_CMD_GET_RSS_INDIR_TABLE,
	SPNIC_UCODE_CMD_GET_RSS_CONTEXT_TABLE,
	SPNIC_UCODE_CMD_SET_IQ_ENABLE,
	SPNIC_UCODE_CMD_SET_RQ_FLUSH = 10,
	SPNIC_UCODE_CMD_MODIFY_VLAN_CTX,
	SPNIC_UCODE_CMD_DPI_FLOW
} cmdq_nic_subtype_e;

/*
 * Commands between NIC and MPU
 */
enum spnic_cmd {
	SPNIC_CMD_VF_REGISTER = 0, /* only for PFD and VFD */

	/* FUNC CFG */
	SPNIC_CMD_SET_FUNC_TBL = 5,
	SPNIC_CMD_SET_VPORT_ENABLE,
	SPNIC_CMD_SET_RX_MODE,
	SPNIC_CMD_SQ_CI_ATTR_SET,
	SPNIC_CMD_GET_VPORT_STAT,
	SPNIC_CMD_CLEAN_VPORT_STAT,
	SPNIC_CMD_CLEAR_QP_RESOURCE,
	SPNIC_CMD_CFG_FLEX_QUEUE,
	/* LRO CFG */
	SPNIC_CMD_CFG_RX_LRO,
	SPNIC_CMD_CFG_LRO_TIMER,
	SPNIC_CMD_FEATURE_NEGO,

	/* MAC & VLAN CFG */
	SPNIC_CMD_GET_MAC = 20,
	SPNIC_CMD_SET_MAC,
	SPNIC_CMD_DEL_MAC,
	SPNIC_CMD_UPDATE_MAC,
	SPNIC_CMD_GET_ALL_DEFAULT_MAC,

	SPNIC_CMD_CFG_FUNC_VLAN,
	SPNIC_CMD_SET_VLAN_FILTER_EN,
	SPNIC_CMD_SET_RX_VLAN_OFFLOAD,

	/* SR-IOV */
	SPNIC_CMD_CFG_VF_VLAN = 40,
	SPNIC_CMD_SET_SPOOPCHK_STATE,
	/* RATE LIMIT */
	SPNIC_CMD_SET_MAX_MIN_RATE,

	/* RSS CFG */
	SPNIC_CMD_RSS_CFG = 60,
	SPNIC_CMD_RSS_TEMP_MGR,
	SPNIC_CMD_GET_RSS_CTX_TBL,
	SPNIC_CMD_CFG_RSS_HASH_KEY,
	SPNIC_CMD_CFG_RSS_HASH_ENGINE,
	SPNIC_CMD_GET_INDIR_TBL,

	/* DPI/FDIR */
	SPNIC_CMD_ADD_TC_FLOW = 80,
	SPNIC_CMD_DEL_TC_FLOW,
	SPNIC_CMD_GET_TC_FLOW,
	SPNIC_CMD_FLUSH_TCAM,
	SPNIC_CMD_CFG_TCAM_BLOCK,
	SPNIC_CMD_ENABLE_TCAM,
	SPNIC_CMD_GET_TCAM_BLOCK,

	/* PORT CFG */
	SPNIC_CMD_SET_PORT_ENABLE = 100,
	SPNIC_CMD_CFG_PAUSE_INFO,

	SPNIC_CMD_SET_PORT_CAR,
	SPNIC_CMD_SET_ER_DROP_PKT,

	SPNIC_CMD_VF_COS,
	SPNIC_CMD_SETUP_COS_MAPPING,
	SPNIC_CMD_SET_ETS,
	SPNIC_CMD_SET_PFC,

	/* MISC */
	SPNIC_CMD_BIOS_CFG = 120,
	SPNIC_CMD_SET_FIRMWARE_CUSTOM_PACKETS_MSG,

	/* DFX */
	SPNIC_CMD_GET_SM_TABLE = 140,
	SPNIC_CMD_RD_LINE_TBL,

	SPNIC_CMD_MAX = 256
};

/* COMM commands between driver to MPU */
enum spnic_mgmt_cmd {
	MGMT_CMD_FUNC_RESET = 0,
	MGMT_CMD_FEATURE_NEGO,
	MGMT_CMD_FLUSH_DOORBELL,
	MGMT_CMD_START_FLUSH,
	MGMT_CMD_SET_FUNC_FLR,

	MGMT_CMD_SET_CMDQ_CTXT = 20,
	MGMT_CMD_SET_VAT,
	MGMT_CMD_CFG_PAGESIZE,
	MGMT_CMD_CFG_MSIX_CTRL_REG,
	MGMT_CMD_SET_CEQ_CTRL_REG,
	MGMT_CMD_SET_DMA_ATTR,

	MGMT_CMD_GET_MQM_FIX_INFO = 40,
	MGMT_CMD_SET_MQM_CFG_INFO,
	MGMT_CMD_SET_MQM_SRCH_GPA,
	MGMT_CMD_SET_PPF_TMR,
	MGMT_CMD_SET_PPF_HT_GPA,
	MGMT_CMD_SET_FUNC_TMR_BITMAT,

	MGMT_CMD_GET_FW_VERSION = 60,
	MGMT_CMD_GET_BOARD_INFO,
	MGMT_CMD_SYNC_TIME,
	MGMT_CMD_GET_HW_PF_INFOS,
	MGMT_CMD_SEND_BDF_INFO,

	MGMT_CMD_UPDATE_FW = 80,
	MGMT_CMD_ACTIVE_FW,
	MGMT_CMD_HOT_ACTIVE_FW,
	MGMT_CMD_HOT_ACTIVE_DONE_NOTICE,
	MGMT_CMD_SWITCH_CFG,
	MGMT_CMD_CHECK_FLASH,
	MGMT_CMD_CHECK_FLASH_RW,
	MGMT_CMD_RESOURCE_CFG,
	MGMT_CMD_UPDATE_BIOS,

	MGMT_CMD_FAULT_REPORT = 100,
	MGMT_CMD_WATCHDOG_INFO,
	MGMT_CMD_MGMT_RESET,
	MGMT_CMD_FFM_SET,

	MGMT_CMD_GET_LOG = 120,
	MGMT_CMD_TEMP_OP,
	MGMT_CMD_EN_AUTO_RST_CHIP,
	MGMT_CMD_CFG_REG,
	MGMT_CMD_GET_CHIP_ID,
	MGMT_CMD_SYSINFO_DFX,
	MGMT_CMD_PCIE_DFX_NTC,
};

enum mag_cmd {
	SERDES_CMD_PROCESS = 0,

	MAG_CMD_SET_PORT_CFG      = 1,
	MAG_CMD_SET_PORT_ADAPT    = 2,
	MAG_CMD_CFG_LOOPBACK_MODE = 3,

	MAG_CMD_GET_PORT_ENABLE   = 5,
	MAG_CMD_SET_PORT_ENABLE   = 6,
	MAG_CMD_GET_LINK_STATUS   = 7,
	MAG_CMD_SET_LINK_FOLLOW   = 8,
	MAG_CMD_SET_PMA_ENABLE    = 9,
	MAG_CMD_CFG_FEC_MODE      = 10,

	/* PHY */
	MAG_CMD_GET_XSFP_INFO        = 60,
	MAG_CMD_SET_XSFP_ENABLE      = 61,
	MAG_CMD_GET_XSFP_PRESENT     = 62,
	MAG_CMD_SET_XSFP_RW          = 63,
	MAG_CMD_CFG_XSFP_TEMPERATURE = 64,

	MAG_CMD_WIRE_EVENT        = 100,
	MAG_CMD_LINK_ERR_EVENT    = 101,

	MAG_CMD_EVENT_PORT_INFO   = 150,
	MAG_CMD_GET_PORT_STAT     = 151,
	MAG_CMD_CLR_PORT_STAT     = 152,
	MAG_CMD_GET_PORT_INFO     = 153,
	MAG_CMD_GET_PCS_ERR_CNT   = 154,
	MAG_CMD_GET_MAG_CNT       = 155,
	MAG_CMD_DUMP_ANTRAIN_INFO = 156,

	MAG_CMD_MAX = 0xFF
};

#endif /* _SPNIC_CMD_H_ */
