/* SPDX-License-Identifier: BSD-3-Clause
 * Copyright(c) 2021 Ramaxel Memory Technology, Ltd
 */

#ifndef _SPNIC_CSR_H_
#define _SPNIC_CSR_H_

#define PCI_VENDOR_ID_RAMAXEL			0x1E81

/* Device ids */
#define SPNIC_DEV_ID_PF				0x9020
#define SPNIC_DEV_ID_VF				0x9001

/*
 * Bit30/bit31 for bar index flag
 * 00: bar0
 * 01: bar1
 * 10: bar2
 * 11: bar3
 */
#define SPNIC_CFG_REGS_FLAG			0x40000000

#define SPNIC_MGMT_REGS_FLAG			0xC0000000

#define SPNIC_REGS_FLAG_MAKS			0x3FFFFFFF

#define SPNIC_VF_CFG_REG_OFFSET                 0x2000

#define SPNIC_HOST_CSR_BASE_ADDR		(SPNIC_MGMT_REGS_FLAG + 0x6000)
#define SPNIC_CSR_GLOBAL_BASE_ADDR		(SPNIC_MGMT_REGS_FLAG + 0x6400)

/* HW interface registers */
#define SPNIC_CSR_FUNC_ATTR0_ADDR		(SPNIC_CFG_REGS_FLAG + 0x0)
#define SPNIC_CSR_FUNC_ATTR1_ADDR		(SPNIC_CFG_REGS_FLAG + 0x4)
#define SPNIC_CSR_FUNC_ATTR2_ADDR		(SPNIC_CFG_REGS_FLAG + 0x8)
#define SPNIC_CSR_FUNC_ATTR3_ADDR		(SPNIC_CFG_REGS_FLAG + 0xC)
#define SPNIC_CSR_FUNC_ATTR4_ADDR		(SPNIC_CFG_REGS_FLAG + 0x10)
#define SPNIC_CSR_FUNC_ATTR5_ADDR		(SPNIC_CFG_REGS_FLAG + 0x14)
#define SPNIC_CSR_FUNC_ATTR6_ADDR		(SPNIC_CFG_REGS_FLAG + 0x18)

#define SPNIC_FUNC_CSR_MAILBOX_DATA_OFF	0x80
#define SPNIC_FUNC_CSR_MAILBOX_CONTROL_OFF	(SPNIC_CFG_REGS_FLAG + 0x0100)
#define SPNIC_FUNC_CSR_MAILBOX_INT_OFFSET_OFF	(SPNIC_CFG_REGS_FLAG + 0x0104)
#define SPNIC_FUNC_CSR_MAILBOX_RESULT_H_OFF	(SPNIC_CFG_REGS_FLAG + 0x0108)
#define SPNIC_FUNC_CSR_MAILBOX_RESULT_L_OFF	(SPNIC_CFG_REGS_FLAG + 0x010C)

#define SPNIC_PPF_ELECTION_OFFSET		0x0
#define SPNIC_MPF_ELECTION_OFFSET		0x20

#define SPNIC_CSR_PPF_ELECTION_ADDR		\
			(SPNIC_HOST_CSR_BASE_ADDR + SPNIC_PPF_ELECTION_OFFSET)

#define SPNIC_CSR_GLOBAL_MPF_ELECTION_ADDR		\
			(SPNIC_HOST_CSR_BASE_ADDR + SPNIC_MPF_ELECTION_OFFSET)

#define SPNIC_CSR_DMA_ATTR_TBL_ADDR		(SPNIC_CFG_REGS_FLAG + 0x380)
#define SPNIC_CSR_DMA_ATTR_INDIR_IDX_ADDR	(SPNIC_CFG_REGS_FLAG + 0x390)

/* MSI-X registers */
#define SPNIC_CSR_MSIX_INDIR_IDX_ADDR		(SPNIC_CFG_REGS_FLAG + 0x310)
#define SPNIC_CSR_MSIX_CTRL_ADDR		(SPNIC_CFG_REGS_FLAG + 0x300)
#define SPNIC_CSR_MSIX_CNT_ADDR		        (SPNIC_CFG_REGS_FLAG + 0x304)
#define SPNIC_CSR_FUNC_MSI_CLR_WR_ADDR		(SPNIC_CFG_REGS_FLAG + 0x58)

#define SPNIC_MSI_CLR_INDIR_RESEND_TIMER_CLR_SHIFT	0
#define SPNIC_MSI_CLR_INDIR_INT_MSK_SET_SHIFT		1
#define SPNIC_MSI_CLR_INDIR_INT_MSK_CLR_SHIFT		2
#define SPNIC_MSI_CLR_INDIR_AUTO_MSK_SET_SHIFT		3
#define SPNIC_MSI_CLR_INDIR_AUTO_MSK_CLR_SHIFT		4
#define SPNIC_MSI_CLR_INDIR_SIMPLE_INDIR_IDX_SHIFT	22

#define SPNIC_MSI_CLR_INDIR_RESEND_TIMER_CLR_MASK	0x1U
#define SPNIC_MSI_CLR_INDIR_INT_MSK_SET_MASK		0x1U
#define SPNIC_MSI_CLR_INDIR_INT_MSK_CLR_MASK		0x1U
#define SPNIC_MSI_CLR_INDIR_AUTO_MSK_SET_MASK		0x1U
#define SPNIC_MSI_CLR_INDIR_AUTO_MSK_CLR_MASK		0x1U
#define SPNIC_MSI_CLR_INDIR_SIMPLE_INDIR_IDX_MASK	0x3FFU

#define SPNIC_MSI_CLR_INDIR_SET(val, member)		\
		(((val) & SPNIC_MSI_CLR_INDIR_##member##_MASK) << \
		SPNIC_MSI_CLR_INDIR_##member##_SHIFT)

/* EQ registers */
#define SPNIC_AEQ_INDIR_IDX_ADDR		(SPNIC_CFG_REGS_FLAG + 0x210)

#define SPNIC_AEQ_MTT_OFF_BASE_ADDR		(SPNIC_CFG_REGS_FLAG + 0x240)

#define SPNIC_CSR_EQ_PAGE_OFF_STRIDE			8

#define SPNIC_AEQ_HI_PHYS_ADDR_REG(pg_num)	\
		(SPNIC_AEQ_MTT_OFF_BASE_ADDR + \
		(pg_num) * SPNIC_CSR_EQ_PAGE_OFF_STRIDE)

#define SPNIC_AEQ_LO_PHYS_ADDR_REG(pg_num)	\
		(SPNIC_AEQ_MTT_OFF_BASE_ADDR + \
		(pg_num) * SPNIC_CSR_EQ_PAGE_OFF_STRIDE + 4)

#define SPNIC_CSR_AEQ_CTRL_0_ADDR		(SPNIC_CFG_REGS_FLAG + 0x200)
#define SPNIC_CSR_AEQ_CTRL_1_ADDR		(SPNIC_CFG_REGS_FLAG + 0x204)
#define SPNIC_CSR_AEQ_CONS_IDX_ADDR		(SPNIC_CFG_REGS_FLAG + 0x208)
#define SPNIC_CSR_AEQ_PROD_IDX_ADDR		(SPNIC_CFG_REGS_FLAG + 0x20C)
#define SPNIC_CSR_AEQ_CI_SIMPLE_INDIR_ADDR	(SPNIC_CFG_REGS_FLAG + 0x50)

#endif /* _SPNIC_CSR_H_ */
