

#include "nthw_fpga_mod_str_map.h"
const struct nthw_fpga_mod_str_s sa_nthw_fpga_mod_str_map[] = { { MOD_CAT, "CAT" },
	{ MOD_CB, "CB" },
	{ MOD_COR, "COR" },
	{ MOD_CPY, "CPY" },
	{ MOD_CSU, "CSU" },
	{ MOD_DBS, "DBS" },
	{ MOD_DDP, "DDP" },
	{ MOD_EPP, "EPP" },
	{ MOD_EQM, "EQM" },
	{ MOD_FHM, "FHM" },
	{ MOD_FLM, "FLM" },
	{ MOD_GFG, "GFG" },
	{ MOD_GMF, "GMF" },
	{ MOD_GPIO_PHY, "GPIO_PHY" },
	{
		MOD_GPIO_PHY_PORTS,
		"GPIO_PHY_PORTS"
	},
	{ MOD_GPIO_SFPP, "GPIO_SFPP" },
	{ MOD_HFU, "HFU" },
	{ MOD_HIF, "HIF" },
	{ MOD_HSH, "HSH" },
	{ MOD_I2CM, "I2CM" },
	{ MOD_IFR, "IFR" },
	{ MOD_IGAM, "IGAM" },
	{ MOD_IIC, "IIC" },
	{ MOD_INS, "INS" },
	{ MOD_IOA, "IOA" },
	{ MOD_IPF, "IPF" },
	{ MOD_KM, "KM" },
	{ MOD_MAC, "MAC" },
	{ MOD_MAC_PCS, "MAC_PCS" },
	{ MOD_MAC_PCS_XXV, "MAC_PCS_XXV" },
	{ MOD_MAC_RX, "MAC_RX" },
	{ MOD_MAC_TFG, "MAC_TFG" },
	{ MOD_MAC_TX, "MAC_TX" },
	{ MOD_MSK, "MSK" },
	{ MOD_PCIE3, "PCIE3" },
	{ MOD_PCI_RD_TG, "PCI_RD_TG" },
	{ MOD_PCI_TA, "PCI_TA" },
	{ MOD_PCI_WR_TG, "PCI_WR_TG" },
	{ MOD_PCS, "PCS" },
	{ MOD_PCS100, "PCS100" },
	{ MOD_PDB, "PDB" },
	{ MOD_PDI, "PDI" },
	{ MOD_PHY_TILE, "PHY_TILE" },
	{ MOD_QSL, "QSL" },
	{ MOD_QSPI, "QSPI" },
	{ MOD_R2DRP, "R2DRP" },
	{ MOD_RAC, "RAC" },
	{ MOD_RFD, "RFD" },
	{ MOD_RMC, "RMC" },
	{ MOD_ROA, "ROA" },
	{ MOD_RPF, "RPF" },
	{ MOD_RPL, "RPL" },
	{ MOD_RPP_LR, "RPP_LR" },
	{ MOD_RST9563, "RST9563" },
	{ MOD_SDC, "SDC" },
	{ MOD_SLC, "SLC" },
	{ MOD_SLC_LR, "SLC_LR" },
	{ MOD_SPIM, "SPIM" },
	{ MOD_SPIS, "SPIS" },
	{ MOD_STA, "STA" },
	{ MOD_TEMPMON, "TEMPMON" },
	{ MOD_TINT, "TINT" },
	{ MOD_TSM, "TSM" },
	{ MOD_TX_CPY, "TX_CPY" },
	{ MOD_TX_CSI, "TX_CSI" },
	{ MOD_TX_CSO, "TX_CSO" },
	{ MOD_TX_INS, "TX_INS" },
	{ MOD_TX_RPL, "TX_RPL" },
	{ 0UL, NULL }
};

/* EOF */
