#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
# Copyright(c) 2025 Microsoft Corporation

"""
This script generates a table which lists the flags indicating which instruction sets are
supported for each CPU type.
The CPU names are stored in file cpu-names.txt, which is consumed by this script.
The script relies on the information embedded in the g++ compiler. This means that an updated
table can automatically be generated by switching to a newer version of the compiler.
The only thing that might need be done is adding new CPU names to cpu-names.txt, when new
CPUs are released in the market.

NOTE: CPUs not known to the compiler will result in errors, which can be ignored (this script
will ignore these errors and continue). For best results use the latest g++ compiler available.
"""

import subprocess

with open("cpu-names.txt", "r") as file:
    for line in file:
        line = line.strip()
        if line.startswith("#") or line == "":
            continue

        words = line.split(",")
        cpu_name = words[0].strip()
        if len(words) > 1:
            nbits = words[1].strip()
        else:
            nbits = ""

        if nbits == "32":
            result = subprocess.run(["g++", "dump-cpu-flags.cpp", "-o",
                                     "dump-cpu-flags", f"-march={cpu_name}", "-m32"])
        else:
            result = subprocess.run(["g++", "dump-cpu-flags.cpp", "-o",
                                     "dump-cpu-flags", f"-march={cpu_name}"])

        if result.returncode == 0:
            subprocess.run(["./dump-cpu-flags", cpu_name])
