# SPDX-License-Identifier: BSD-3-Clause
# Copyright(c) 2020 Siemens AG

include $(RTE_SDK)/mk/rte.vars.mk

APP = l2reflect

CFLAGS += $(WERROR_FLAGS)

# all source are stored in SRCS-y

SRCS-y := main.c stats.c

include $(RTE_SDK)/mk/rte.app.mk
