# SPDX-License-Identifier: BSD-3-Clause
# Copyright(c) 2024 The DPDK contributors
# This file is automatically generated by generate-test-mappings.py.
# Do NOT modify this file manually.

"""Generated file containing the links between the test suites and the configuration."""

from typing import TYPE_CHECKING, Optional

from framework.config.test_suite import BaseTestSuitesConfigs, TestSuiteConfig

if TYPE_CHECKING:
    from tests.TestSuite_hello_world import HelloWorldConfig


CUSTOM_CONFIG_TYPES: dict[str, type[TestSuiteConfig]] = {}


class TestSuitesConfigs(BaseTestSuitesConfigs):
    """Configuration mapping class to select and configure the test suites.

    Before using this class, the custom configuration type annotations need to be fixed.
    To do so, you need to call the `fix_custom_config_annotations` method.
    """

    hello_world: Optional["HelloWorldConfig"] = None
    os_udp: Optional[TestSuiteConfig] = None
    pmd_buffer_scatter: Optional[TestSuiteConfig] = None

    @classmethod
    def fix_custom_config_annotations(cls):
        """Fixes the custom config types annotations.

        Moreover it also fills `CUSTOM_CONFIG_TYPES` with all the custom config types.
        """
        from tests.TestSuite_hello_world import HelloWorldConfig

        CUSTOM_CONFIG_TYPES["hello_world"] = HelloWorldConfig

        cls.model_rebuild()
